# Generated by Django 4.1.7 on 2023-03-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_ride_end_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='payment',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.payment'),
        ),
    ]
