# Generated by Django 4.1.7 on 2023-03-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_ride_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'Bike'), ('SEDAN', 'Car_Sedan'), ('SUV', 'Car_Suv'), ('RIK', 'Rikshaw')], default='SEDAN', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seat_capacity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
