# Generated by Django 4.1.7 on 2023-03-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_vehicle_vehicle_type_alter_vehicle_mileage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='end_destination_lon',
            new_name='end_destination_lng',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='start_destination_lon',
            new_name='start_destination_lng',
        ),
        migrations.RenameField(
            model_name='triplocations',
            old_name='lon',
            new_name='lng',
        ),
        migrations.AlterField(
            model_name='ride',
            name='state',
            field=models.CharField(choices=[('s', 'started'), ('i', 'driver incoming'), ('p', 'pickup ready'), ('o', 'ongoing'), ('f', 'finished'), ('c', 'cancelled')], default='s', max_length=1),
        ),
    ]
