# Generated by Django 4.1.7 on 2023-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='from_location',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='to_location',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
