# Generated by Django 4.1.7 on 2023-05-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_ride_from_location_ride_to_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='state',
            field=models.CharField(choices=[('b', 'booked'), ('s', 'started'), ('i', 'driver incoming'), ('p', 'pickup ready'), ('o', 'ongoing'), ('f', 'finished'), ('c', 'cancelled')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'Bike'), ('SEDAN', 'Car_Sedan'), ('SUV', 'Car_Suv'), ('RIK', 'Rikshaw'), ('BUS', 'Bus')], default='SEDAN', max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='BookedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_destination_lat', models.FloatField(default=None, null=True)),
                ('start_destination_lng', models.FloatField(default=None, null=True)),
                ('end_destination_lat', models.FloatField(default=None, null=True)),
                ('end_destination_lng', models.FloatField(default=None, null=True)),
                ('from_location', models.CharField(default=None, max_length=256, null=True)),
                ('to_location', models.CharField(default=None, max_length=256, null=True)),
                ('pickup_time', models.DateTimeField()),
                ('drop_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('state', models.CharField(choices=[('b', 'booked'), ('c', 'cancelled')], default='b', max_length=1)),
                ('driver_history', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_trip_history', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.payment')),
                ('user_history', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_trip_history', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.vehicle')),
            ],
        ),
    ]
