# Generated by Django 4.1.7 on 2023-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_driver_for_trip_alter_ride_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='for_trip',
        ),
        migrations.AddField(
            model_name='user',
            name='for_trip',
            field=models.BooleanField(default=False),
        ),
    ]
