# Generated by Django 4.1.7 on 2023-05-28 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_driver_for_trip_user_for_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
